#!/bin/bash

#########################################################
# Xavier Demompion : xavier.demompion@mobile-devices.fr
# Mobile Devices 2013
#########################################################

commands=' stop_admin start_admin start stop read_log_server_config read_log_server read_log_agents restart_admin restart '
command=$1
params=${@:2}

if [ "$command" = '' ] || ! [[ $commands =~ \ $command\  ]] ; then
  echo -e "\033[31m$0 command\033[0m\n\033[032mAvailable commands are: $commands\033[0m"
  exit 1
fi

#launch admin server
start_admin() {
  echo "starting admin server"
  pushd . >> /dev/null
  cd web_shell/local_cloud_config
  ruby local_cloud_config.rb >>../../logs/daemon_server_config.log 2>&1 &
  popd >> /dev/null
  build_doc >> /dev/null &
}

stop_admin() {
  pkill -f 'ruby local_cloud_config.rb'
}

restart_admin() {
  stop_admin
  start_admin
}

start() {
  pushd . >> /dev/null
  cd web_shell/local_cloud
  ./local_cloud.sh restart
  popd >> /dev/null
}

stop() {
  pushd . >> /dev/null
  cd web_shell/local_cloud
  ./local_cloud.sh stop
  popd >> /dev/null
}

restart() {
  stop
  start
}

read_log_server_config() {
  tail -f logs/daemon_server_config.log
}

read_log_server() {
  tail -f logs/daemon_server.log
}

#todo: test if multitail available, multi tail only run agent
read_log_agents() {
  tail -f logs/ruby-agent-sdk-server.log
}

build_doc() {
  pushd . >> /dev/null
  cd web_shell/local_cloud
  bundle exec yardoc
  popd >> /dev/null
}

$command $params
