#!/bin/bash

commands=' start_admin start stop read_server_log read_agents_log '
command=$1
params=${@:2}

if [ "$command" = '' ] || ! [[ $commands =~ \ $command\  ]] ; then
  echo -e "\033[31m$0 command\033[0m\n\033[032mAvailable commands are: $commands\033[0m"
  exit 1
fi

#launch admin server
start_admin() {
  echo "starting admin server"
  cd web_shell/VM-Framework
  ruby local_cloud_config.rb > /home/vagrant/ruby_workspace/sdk_logs/local_cloud_config.ruby.log &
}

start() {
    cd web_shell/VM-Framework
    ./local_cloud.sh restart
}

stop() {
    cd web_shell/VM-Framework
    ./local_cloud.sh stop
}

read_server_log() {
  cd web_shell/logs
  tail -f ruby-agents-sdk.log
}

#todo: test if multitail available, multi tail only run agent
read_agents_log() {
  multitail web_shell/logs/agents/ruby_log_*
}

$command $params