#!/bin/bash

commands=' stop_admin start_admin start stop read_server_log read_agents_log read_admin_server_log '
command=$1
params=${@:2}

if [ "$command" = '' ] || ! [[ $commands =~ \ $command\  ]] ; then
  echo -e "\033[31m$0 command\033[0m\n\033[032mAvailable commands are: $commands\033[0m"
  exit 1
fi


#launch admin server
start_admin() {
  echo "starting admin server"
  [ ! -d ruby_workspace ] && mkdir ruby_workspace
  cd web_shell/VM-Framework
  ruby local_cloud_config.rb >../../logs/local_cloud_config.ruby.log 2>&1 &
}

stop_admin() {
  for id in `ps -ef | grep -i -e 'ruby local_cloud_config.rb' | awk '{ print $2 }'`; do
    echo "killing pid $id"
    kill -9 $id
  done
}

start() {
    cd web_shell/VM-Framework
    ./local_cloud.sh restart
}

stop() {
    cd web_shell/VM-Framework
    ./local_cloud.sh stop
}

read_admin_server_log() {
  tail -f logs/local_cloud_config.ruby.log
}

read_server_log() {
  tail -f logs/ruby-agents-sdk.log
}

#todo: test if multitail available, multi tail only run agent
read_agents_log() {
  multitail logs/agents/ruby_log_*
}

$command $params