#!/bin/bash

#########################################################
# Xavier Demompion : xavier.demompion@mobile-devices.fr
# Mobile Devices 2013
#########################################################

# note exectued at each vm boot

echo ""
echo "init vm"

export PATH="$HOME/.rbenv/versions/2.1.0/bin/:$HOME/.rbenv/versions/1.9.3-p125/bin/:$HOME/.rbenv/bin:$PATH"
echo $PATH
echo $(rbenv -v)
echo $(ruby -v)

# install sdk gems
echo ""
echo "sdk gem install"
cd /home/vagrant/ruby-agents-sdk/web_shell/local_cloud;cp Gemfile.master Gemfile; bundle install
cd /home/vagrant/ruby-agents-sdk/web_shell/local_cloud_config; bundle install
cd /home/vagrant/ruby-agents-sdk/web_shell/local_cloud/ragent_bay/builder; bundle install

# bind workspace
echo ""
echo "mouting workspace"
mkdir -p /home/vagrant/ruby-agents-sdk/cloud_agents
sudo mount -o bind /home/vagrant/ruby_workspace /home/vagrant/ruby-agents-sdk/cloud_agents
mkdir -p /home/vagrant/ruby-agents-sdk/logs
sudo mount -o bind /home/vagrant/ruby_workspace/sdk_logs /home/vagrant/ruby-agents-sdk/logs
mkdir -p /home/vagrant/ruby-agents-sdk/output
sudo mount -o bind /home/vagrant/ruby_workspace/output /home/vagrant/ruby-agents-sdk/output
mkdir -p /home/vagrant/ruby_workspace/file_storage
sudo mount -o bind /home/vagrant/ruby_workspace/file_storage /home/vagrant/ruby-agents-sdk/file_storage