default: &DEFAULT
  dynamic_channel_str: com.mdi.services.XXProjectName
  subscribe_presence: false
  subscribe_message: false
  subscribe_track: false
  subscribe_collection: false
  subscribe_cloud_event: false

development: *DEFAULT
production: *DEFAULT
