# This is you config yml where you configure functionnal aspect of your agent
# you can have a different configuration when you are in dev or in production mdi cloud if you wish to. In this case both use a default configuration.


default: &DEFAULT
  ############## presences ###########################
  # set to true if you want to receive presences
  subscribe_presence: false

  ############## messages ############################
  # set to true if you want to receive messages
  subscribe_message: false
   # can be a single string or an array of string (ex dynamic_channel_str)
  message_whitelist_channels: com.mdi.services.XXProjectName
  # if you need to output somme content to the cloud, please specify your output here
  message_injection_whitelist_channels: com.mdi.services.XXProjectName


  ############## tracks ##############################
  # set to true if you want to receive tracks
  subscribe_track: false
  # can be a single string, an array of string (['GPS_SPEED','GPS_DIR'] is set as an example, please put your needed fields).
  track_whitelist_fields: ['GPS_SPEED','GPS_DIR']
  # you will only be able to fetch last values of whitelisted fields
  # 0: no last value will be available
  # 1: last values are available
  track_keep_last_known_values_mode: 0
  track_remove_position: false
  track_remove_time: false

  # if you need to output somme content to the cloud, please specify your output here (['ENH_MY_OUTPUT_FIELD'] is set as an example, please put your needed fields).
  track_injection_whitelist_fields: ['ENH_MY_OUTPUT_FIELD']



  # if your functionnalities require to have new field created in the cloud, please create them bellow (following the example):




  ############## collections #########################
  # set to true if you want to receive collections
  subscribe_collection: false

  ############## pokes ###############################
  # set to true if you want to receive pokes
  subscribe_poke: false


  ############## cloud events ########################
  # set to true if you want to receive generics cloud events
  subscribe_cloud_event: false

  ### PUT YOUR SPECIFIC CONFIGURATION BELOW ##########





  ####################################################

development: *DEFAULT
production: *DEFAULT
