source 'http://rubygems.org'

gem 'sinatra'
gem 'hashie'
gem 'json'
gem 'thread'
gem 'logger'
gem 'thin'
gem 'redis'
gem 'redis-namespace'
gem 'redcarpet'
gem 'activesupport', :require => "active_support/all"
